version: '3'

services:
  mkdocs:
    build: ./docker
    ports:
      - 8000:8000
    volumes:
      - ./:/docs
      - ~/.ssh:/root/.ssh:ro
    environment:
      USER_EMAIL: ${USER_EMAIL}
      USER_NAME: ${USER_NAME}
