version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:lts-buster
jobs:
  deploy:
    executor:
        name: default
    steps:
      - checkout
      - setup_remote_docker
      - run:
            name: mount to docker
            command: docker-compose up -d && docker cp ./ $(docker-compose ps -q mkdocs):/docs
      - run:
            name: deploy
            command: |
                mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
                docker-compose run mkdocs mkdocs gh-deploy
workflows:
  setup_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
                only: master
