version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: ubuntu:18.04
jobs:
  deploy:
    executor:
        name: default
    steps:
      - checkout
      - run:
            name: check
            command: ls
      - run:
            name: check2
            command: pwd
workflows:
  setup_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
                only: master
