version: 2.1
executors:
  default:
    working_directory: ~/workspace
    machine:
      image: circleci/node:lts-buster
jobs:
  deploy:
    executor:
        name: default
    steps:
      - checkout
    #   - setup_remote_docker
      - run:
            name: deploy
            command: docker info
workflows:
  setup_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
                only: master
