version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:lts-buster
jobs:
  build:
    executor:
        name: default
    steps:
      - checkout
      - setup_remote_docker
      - run:
            name: mount to docker
            command: docker-compose up -d && docker cp ./ $(docker-compose ps -q mkdocs):/docs
      - run:
            name: build and copy
            command: |
                docker-compose run mkdocs mkdocs build
                docker cp $(docker-compose ps -q mkdocs):/docs/site ./
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - site/
  deploy:
    executor: 
        name: default
    steps:
      - checkout
      - run:
            name: checkout
            command: |
                git checkout gh-pages
      - run:
            name: deploy
            command: |
                cp -r -f ./site/* ./
                git add -A
                git config --global user.name "circle ci"
                git config --global user.email "user@example.com"
                git commit -m "circle ci"
                git push origin gh-pages
workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
                only: master
