version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: ubuntu:18.04
jobs:
  hello:
    executor:
        name: default
    steps:
      - checkout
      - run:
            name: hello step
            command: env
workflows:
  setup_and_deploy:
    jobs:
      - hello:
          filters:
            branches:
                only: master
