version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: docker/compose:debian-1.26.0-rc3
jobs:
  deploy:
    executor:
        name: default
    steps:
      - checkout
      - run:
            name: deploy
            # command: sh ./deploy.sh
            command: which docker
      - run:
            name: deploy
            # command: sh ./deploy.sh
            command: which docker-compose
workflows:
  setup_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
                only: master
